#!/bin/sh

./test$1$2 >test$1.out
RC=$?
if test $RC -eq 0 ; then
	cmp test$1.out test$1.cmp
	RC=$?
fi

if test $RC -eq 0 ; then
	if test $1 -eq 5 ; then
		cmp test$1.csv test$1B.csv
		RC=$?
	fi
fi

exit $RC

# End
